

Product.create name: "Bicicleta de montaña", date_limit:(Date.today+1.day), user: "biciprix@gmail.com", price: 200, description: "Nuevo: Un artículo nuevo, sin usar, sin abrir, sin desperfectos y en el paquete original (en caso de venir empaquetado). El empaquetado debe ser el mismo que se encontraría en una tienda, a menos que el artículo haya sido empaquetado por el fabricante con material no destinado a su venta en tienda (por ejemplo una bolsa o caja sin etiquetas). Consulta el anuncio del vendedor si deseas más información."
Product.create name: "Cable USB de datos", date_limit:(Date.today+2.day), user: "kawai@gmail.com", price: 1, description: "CABLE USB de datos cargador iPhone 5,5S,6, iPad Mini ,8 Pin Máxima Calidad ios 8"
Product.create name: "Teléfono móvil", date_limit:(Date.today+3.day), user: "easybuy@gmail.com", price: 224, description: "ZTE Blade S6 HD 4G Android 5.0 L Smartphone Octa Core Teléfono 2GB+16GB GPS"
Product.create name: "Palo selfie", date_limit:(Date.today+3.day), user: "coccolarsi@gmail.com", price: 10, description: "SELFIE PALO BRAZO EXTENSIBLE MONOPOD MANDO BLUETOOTH+SOPORTE PARA IPHONE ANDROID"
Product.create name: "Cinta de correr", date_limit:(Date.today+3.day), user: "outlet@gmail.com", price: 249, description: "Un artículo nuevo, sin usar, sin abrir, sin desperfectos y en el paquete original (en caso de venir empaquetado). El empaquetado debe ser el mismo que se encontraría en una tienda, a menos que el artículo haya sido empaquetado por el fabricante con material no destinado a su venta en tienda (por ejemplo una bolsa o caja sin etiquetas)."
Product.create name: "Máquina de esquilar", date_limit:(Date.today+2.day), user: "vidaxl@gmail.com", price: 88, description: "Máquina de esquilar eléctrica para oveja Maquina Esquilar Trasquilar Esquiladora. Este set de esquilar para ovejas consiste en: Una máquina de esquilar de ovejas, un destornillador especial, 2 cepillos de carbono especiales, 1 botella de aceite lubricante especial, 1 cepillo de limpieza y 1 caja de transporte y almacenamiento. Este set profecional para ovejas es adecuado para la lana de oveja normal. Los brazos son ergonómicos pues muy cómodos y fáciles de usar. También hay un extra cable largo incluido."
Product.create name: "Cortacesped", date_limit:(Date.today+4.day), user: "agroverd@gmail.com", price: 119, description: "El cortacésped GLM410-16 está concebido para parcelas de entre 100 y 600 m2, es una máquina fácil de usar gracias al paro motor de seguridad el cual para automáticamente la máquina en cuanto de deja de accionar y su bajo mantenimiento."
Product.create name: "Bicicleta de montaña", date_limit:(Date.today+5.day), user: "biciprix@gmail.com", price: 200, description: "Nuevo: Un artículo nuevo, sin usar, sin abrir, sin desperfectos y en el paquete original (en caso de venir empaquetado). El empaquetado debe ser el mismo que se encontraría en una tienda, a menos que el artículo haya sido empaquetado por el fabricante con material no destinado a su venta en tienda (por ejemplo una bolsa o caja sin etiquetas). Consulta el anuncio del vendedor si deseas más información."
Product.create name: "Cable USB de datos", date_limit:(Date.today+6.day), user: "kawai@gmail.com", price: 1, description: "CABLE USB de datos cargador iPhone 5,5S,6, iPad Mini ,8 Pin Máxima Calidad ios 8"
Product.create name: "Teléfono móvil", date_limit:(Date.today+7.day), user: "easybuy@gmail.com", price: 224, description: "ZTE Blade S6 HD 4G Android 5.0 L Smartphone Octa Core Teléfono 2GB+16GB GPS"
Product.create name: "Palo selfie", date_limit:(Date.today+8.day), user: "coccolarsi@gmail.com", price: 10, description: "SELFIE PALO BRAZO EXTENSIBLE MONOPOD MANDO BLUETOOTH+SOPORTE PARA IPHONE ANDROID"
Product.create name: "Cinta de correr", date_limit:(Date.today-1.day), user: "outlet@gmail.com", price: 249, description: "Un artículo nuevo, sin usar, sin abrir, sin desperfectos y en el paquete original (en caso de venir empaquetado). El empaquetado debe ser el mismo que se encontraría en una tienda, a menos que el artículo haya sido empaquetado por el fabricante con material no destinado a su venta en tienda (por ejemplo una bolsa o caja sin etiquetas)."
Product.create name: "Máquina de esquilar", date_limit:(Date.today+5.day), user: "vidaxl@gmail.com", price: 88, description: "Máquina de esquilar eléctrica para oveja Maquina Esquilar Trasquilar Esquiladora. Este set de esquilar para ovejas consiste en: Una máquina de esquilar de ovejas, un destornillador especial, 2 cepillos de carbono especiales, 1 botella de aceite lubricante especial, 1 cepillo de limpieza y 1 caja de transporte y almacenamiento. Este set profecional para ovejas es adecuado para la lana de oveja normal. Los brazos son ergonómicos pues muy cómodos y fáciles de usar. También hay un extra cable largo incluido."
Product.create name: "Cortacesped", date_limit:(Date.today-2.day), user: "agroverd@gmail.com", price: 119, description: "El cortacésped GLM410-16 está concebido para parcelas de entre 100 y 600 m2, es una máquina fácil de usar gracias al paro motor de seguridad el cual para automáticamente la máquina en cuanto de deja de accionar y su bajo mantenimiento."

50.times do
	rand_product_id = (rand Product.count) +1
	p = Product.find rand_product_id
	email = "#{(0..6).map{('a'..'z').to_a[rand(26)]}.join}@gmail.com"
	bid_offer = p.price + (rand 100)
	p.bids.create date:(Date.today - (rand 5).day), offer: bid_offer, user_offer: email 
end

puts "Semilla plantada correctamente"